
### Definition of armv8 ###
set(CMAKE_SYSTEM_NAME Linux)
set(CMAKE_SYSTEM_PROCESSOR arm)

if (NOT ("$ENV{TOOLSCHAIN_ARMV8_PATH}" STREQUAL ""))
    set(TOOLSCHAIN_PATH "$ENV{TOOLSCHAIN_ARMV8_PATH}")
endif()
if ("${TOOLSCHAIN_PATH}" STREQUAL "")
    set(TOOLSCHAIN_PATH "/root/gcc-arm-8.3-2019.03-x86_64-aarch64-linux-gnu")
endif()
set(TOOLSCHAIN_HOST "${TOOLSCHAIN_PATH}/bin/aarch64-linux-gnu")

if (NOT EXISTS ${TOOLSCHAIN_PATH})
    message(FATAL_ERROR "TOOLSCHAIN_PATH:  \"${TOOLSCHAIN_PATH}\" not exist.")
endif()

#set(CMAKE_SYSROOT /home/devel/rasp-pi-rootfs)
#set(CMAKE_STAGING_PREFIX /home/devel/stage)

set(CMAKE_C_COMPILER "${TOOLSCHAIN_HOST}-gcc")
set(CMAKE_CXX_COMPILER "${TOOLSCHAIN_HOST}-g++")
set(CMAKE_AR "${TOOLSCHAIN_HOST}-ar")

set(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER)
set(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_PACKAGE ONLY)
